export const OrderDetailPageTitle = 'Orders History';
export const OrderDetailReorderSelectedBtnTitle = 'Reorder selected items';
export const OrderDetailReorderAllBtnTitle = 'Reorder all';
export const OrderDetailShippingAddressTitle = 'Shipping address';
export const OrderDetailBillingAddressTitle = 'Billing address';
export const OrderDetailSectionTitle = 'Order Details';
export const OrderDetailOrderIdTitle = 'Order Id: ';
export const OrderDetailDateTitle = 'Order Date: ';
export const OrderDetailPriceModeTitle = 'Price Mode: ';
