export const CUSTOMER_DATA_REQUEST = 'CUSTOMER_DATA_REQUEST';
export const CUSTOMER_DATA_UPDATE = 'CUSTOMER_DATA_UPDATE';
export const LOGIN_DATA_SET_TO_STORAGE = 'LOGIN_DATA_SET_TO_STORAGE';
export const CUSTOMER_PASSWORD_UPDATE = 'CUSTOMER_PASSWORD_UPDATE';
