export const CHECKOUT_DATA_INIT_REQUEST = 'CHECKOUT_DATA_INIT_REQUEST';
export const SEND_CHECKOUT_DATA = 'SEND_CHECKOUT_DATA';
export const CHECKOUT_MUTATE_DELIVERY_ADDRESS = 'CHECKOUT_MUTATE_DELIVERY_ADDRESS';
